//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessingWpfCoreCSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EdgeDetection")]
        public string ImgTypeSelectName {
            get {
                return ((string)(this["ImgTypeSelectName"]));
            }
            set {
                this["ImgTypeSelectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ImgTypeEdgeId {
            get {
                return ((int)(this["ImgTypeEdgeId"]));
            }
            set {
                this["ImgTypeEdgeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EdgeDetection")]
        public string ImgTypeEdgeName {
            get {
                return ((string)(this["ImgTypeEdgeName"]));
            }
            set {
                this["ImgTypeEdgeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ImgTypeGrayScaleId {
            get {
                return ((int)(this["ImgTypeGrayScaleId"]));
            }
            set {
                this["ImgTypeGrayScaleId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrayScale")]
        public string ImgTypeGrayScaleName {
            get {
                return ((string)(this["ImgTypeGrayScaleName"]));
            }
            set {
                this["ImgTypeGrayScaleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ImgTypeBinarizationId {
            get {
                return ((int)(this["ImgTypeBinarizationId"]));
            }
            set {
                this["ImgTypeBinarizationId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Binarization")]
        public string ImgTypeBinarizationName {
            get {
                return ((string)(this["ImgTypeBinarizationName"]));
            }
            set {
                this["ImgTypeBinarizationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ImgTypeGrayScale2DiffId {
            get {
                return ((int)(this["ImgTypeGrayScale2DiffId"]));
            }
            set {
                this["ImgTypeGrayScale2DiffId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrayScale 2Diff")]
        public string ImgTypeGrayScale2DiffName {
            get {
                return ((string)(this["ImgTypeGrayScale2DiffName"]));
            }
            set {
                this["ImgTypeGrayScale2DiffName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ImgTypeColorReversalId {
            get {
                return ((int)(this["ImgTypeColorReversalId"]));
            }
            set {
                this["ImgTypeColorReversalId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColorReversal")]
        public string ImgTypeColorReversalName {
            get {
                return ((string)(this["ImgTypeColorReversalName"]));
            }
            set {
                this["ImgTypeColorReversalName"] = value;
            }
        }
    }
}
